# Generated by Django 5.2.5 on 2025-08-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.post'),
        ),
    ]
